export const page = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Life OS — Project Lantern</title><link rel="stylesheet" href="/life-os/style.css"><script src="/life-os/app.js" defer></script></head>
<body><main><header><p class="brand">PROJECT LANTERN</p><h1>LIFE OS — POC</h1><p>ChatGPT Monitoring Integration Test</p></header><section class="health"><button id="refresh">Refresh now</button><p id="connection" role="status">Loading results…</p><p id="bridge">Email fallback has not reported yet.</p></section><section id="results" aria-label="Monitoring results"></section><footer>Latest 100 results · Checks every 30 seconds while this page is open.</footer></main></body></html>`;
export const styles = `:root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#10151a;color:#e9eef2}body{margin:0}main{max-width:850px;margin:auto;padding:28px 18px}header{padding:20px 0}.brand{letter-spacing:.2em;color:#b8cbd4;font-size:.85rem}h1{font-size:1.8rem}p{line-height:1.6}.health,article{border:1px solid #40515d;border-radius:10px;padding:20px;margin-bottom:18px}article.attention{border-left:5px solid #ffd16b}article.normal{border-left:5px solid #85d5b2}.badge{font-weight:700;color:#85d5b2}.attention .badge{color:#ffd16b}h2{font-size:1.25rem}dl{display:grid;grid-template-columns:120px minmax(0,1fr);gap:10px}dt{color:#acbcc6}dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}button{background:#d3e8f2;color:#14202a;border:0;padding:10px 16px;border-radius:5px;font:inherit;cursor:pointer}button:disabled{opacity:.5}summary{cursor:pointer;padding:10px 0}details p{white-space:pre-wrap;overflow-wrap:anywhere}footer{color:#acbcc6;font-size:.85rem}@media(max-width:480px){dl{grid-template-columns:1fr;gap:5px}dd{margin-bottom:10px}main{padding:18px 12px}}`;
export const script = `const container=document.querySelector('#results');
const connection=document.querySelector('#connection');
const button=document.querySelector('#refresh');
function el(tag,value){const n=document.createElement(tag);n.textContent=value;return n;}
function card(r){const a=el('article','');a.className=r.requires_attention?'attention':'normal';a.append(el('p',r.requires_attention?'NEEDS ATTENTION':'NORMAL'));a.firstChild.className='badge';a.append(el('h2',r.task_name));const dl=el('dl','');for(const [k,v] of [['SUBJECT',r.subject],['STATUS',r.status],['SUMMARY',r.summary],['SOURCE',r.source],['EXECUTED',new Date(r.execution_time).toLocaleString()],['RECEIVED',new Date(r.received_time).toLocaleString()]]){dl.append(el('dt',k),el('dd',v));}a.append(dl);const d=el('details','');d.append(el('summary','DETAILS'),el('p',r.details),el('p','Processing: '+r.processing_status+' · External ID: '+r.external_id+' · ID: '+r.id));a.append(d);return a;}
async function refresh(){if(button.disabled)return;button.disabled=true;try{const response=await fetch('/life-os/api/results',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(response.status===401?'Authentication expired. Reload to sign in.':'Server returned '+response.status);const data=await response.json();container.replaceChildren(...data.results.map(card));if(!data.results.length)container.append(el('p','No results received yet. Run the synthetic pipeline test.'));connection.textContent='Connected · Last checked '+new Date().toLocaleTimeString();const b=data.bridge;document.querySelector('#bridge').textContent=b?'Bridge: '+b.state+' · '+b.message+' · Last check '+new Date(b.checked_time).toLocaleString()+(Date.now()-Date.parse(b.checked_time)>15*60*1000?' · STALE: check the bridge trigger':''):'GitHub deliveries appear below. Email fallback has not reported. Synthetic data does not prove ChatGPT integration.';}catch(e){connection.textContent='Results may be stale · '+e.message;}finally{button.disabled=false;}}
button.addEventListener('click',refresh);refresh();setInterval(refresh,30000);`;
